#board: [ "nice_nano_v2" ]
#shield: [ "azelus3" ]

# deactivate GHA complie for now (build locally only)
#include:
#  - board: nice_nano_v2
#    shield: azelus3
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y

# Build multiple shield firmwares in a single go (TODO)
#  - board: nice_nano_v2
#    shield: redpoll
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#    artifact-name: redpoll_with_studio

#---
