
# enable bluetooth
CONFIG_ZMK_BLE=y
# enable battery reporting
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
# battery reporting for peripheral halves
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Important: Bluetooth security
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Use USB when plugged in
CONFIG_ZMK_USB=y

# enable deep sleep
CONFIG_ZMK_SLEEP=y
# deep sleep after half an hour (default 15mins)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# N-key rollover. "y" when using steno/plover
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n



